import { join } from "path";
import { readFileSync, writeFileSync } from "fs";
/**
 * If someone figures out how to have one util.js file work, let me know. Until then, here we go
 */

function copy(src, changes, dest) {
    const contents = readFileSync(join(import.meta.dirname, src), {encoding: "utf-8"})
    const newContents = 
        "/* This file has been auto-generated using /tip-zorgkaart-goggles/shared/generate.js - Do not edit this file directly. Edit its counterpart in the shared folder and run 'npm run build:shared' or node generate.js */\n" + 
        changes(contents);
    writeFileSync(
        join(import.meta.dirname, dest),
        newContents,
        {encoding: "utf-8"});
}

copy(
    "utils.js",
    (contents) => { return contents; },
    "../browser-extension/utils.js");

copy(
    "utils.js",
    (contents) => { 
        return contents.replace(
            /^function/gm,
            "export function"); },
    "../webpage/src/_data/utils.js");
