name: Build & release web extension

on:
  push:
    tags: [ "*.*.*" ]
  # Allows this workflow to be called from other workflows
  workflow_call:

jobs:
  github-releases:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./browser-extension
    steps:
      - uses: actions/checkout@v4
        with:
          # Select latest ref instead of event trigger, in case this is triggered by another event
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v4
          
      - name: Install pre-requirements
        run: npm ci

      - name: Build web extension ZIP
        run: npm run build
      
      - name: Upload to GitHub Releases
        uses: ncipollo/release-action@v1.16.0
        with:
          artifacts: browser-extension/web-ext-artifacts/*.zip,web-ext-artifacts/*.zip